shared:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: logtensafe

development:
  database: logtensafe_development

test: &test
  host: localhost
  username: <%= ENV.fetch('POSTGRES_USER') { 'tmorgan' } %>
  owner: logtensafe
  password: <%= ENV.fetch('POSTGRES_PASSWORD') { '' } %>
  database: <%= ENV.fetch('POSTGRES_DB') { 'logtensafe_test' } %>

cypress: *test

production:
  database: logtensafe_production
