# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c19aefe0d34d973da0ca9ee3ec2e42be3ef68bbb8ad953322ed5b7924d39286d08e83bae185f660a4a019bb3fa859a248833400d539bcc9ced9f8aa489bc50a

test:
  secret_key_base: ad7e3446aaf266003ed89c32014654ac05c873ad7e372ca853ce755027c4c6079836ae71383ed66744ad96f3f9a6dc1f0608beac4b78207858b7c77507ebb493

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
