development:
  frontend: 'http://localhost:5100'
  backend: 'http://localhost:5100'
  cable: 'ws://localhost:28080/cable'
cypress:
  frontend: 'http://localhost:5100'
  backend: 'http://localhost:5100'
  cable: 'ws://localhost:28080/cable'
test:
  frontend: 'http://frontend.example.com'
  backend: 'http://backend.example.com'
  cable: 'ws://backend.example.com/cable'
production:
  frontend: 'https://logtensafe.com'
  backend: 'https://app.logtensafe.com'
  cable: 'wss://app.logtensafe.com/cable'
